version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresDB:/var/lib/postgresql/data

volumes:
  postgresDB:
    driver_opts:
      type: volume
      o: bind
      device: /home/ubuntu/user-back/data/postgresql
    name: postgresDB
