version: "3"

volumes:
  volume_postgres:
  volume_backend: # 백엔드에서 이미지 저장할 때 필요한 볼륨

networks:
  network-transcendence:
    driver: bridge

services:

  postgresql:
    image: postgres
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - network-transcendence

  backend: # nest
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        IMAGE_SAVE_PATH: ${IMAGE_SAVE_PATH?}
    depends_on:
      - postgresql
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    command: node dist/main.js
    networks:
      - network-transcendence
      - default
    volumes: # 백엔드에서 이미지 저장할 때 필요한 볼륨
      - volume_backend:${IMAGE_SAVE_PATH} # TODO build 하고 mount 하면 빌드할 때 copy 한 게 없어질 것 같긴함

  frontend: # svelte
    restart: always
    build: frontend
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - 5173:5173
    command: npm run dev
    environment:
      VITE_API_URL: ${VITE_API_URL?}
    networks:
      - network-transcendence
      - default
