version: "3"

services:

  postgresql:
    image: postgres
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - network-transcendence

  backend:
    image: nest
    restart: always
    build: backend
    depends_on:
      - postgresql
    env_file:
      - .env
    expose:
      - 3000
    networks:
      - network-inception
    volumes: # 백엔드에서 이미지 저장할 때 필요한 볼륨
      - volume_backend:${IMAGE_SAVE_PATH}

  frontend:
    image: svelte
    restart: always
    build: front
    depends_on:
      - nest
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: ${VITE_API_URL?}
    networks:
      - network-inception

  volumes:
    volume_postgres:

    volume_backend: # 백엔드에서 이미지 저장할 때 필요한 볼륨

  networks:
    network-inception:
      driver: bridge
