version: "3"

volumes:
  volume_postgres:
  volume_backend:

networks:
  network-transcendence:
    driver: bridge

services:

  postgresql:
    image: postgres
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - network-transcendence

  backend: # nest
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        IMAGE_SAVE_PATH: ${IMAGE_SAVE_PATH?}
    depends_on:
      - postgresql
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    command: node dist/main.js
    volumes:
      - volume_backend:/mnt/img
    networks:
      - network-transcendence
      - default

  frontend: # svelte
    restart: always
    build: frontend
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - 5173:5173
    command: npm run --prefix NestJS_Front start:dev
    environment:
      VITE_API_URL: ${VITE_API_URL?}
    networks:
      - network-transcendence
      - default
